"""Cấu hình từ khóa cho weak labeling comment tiếng Việt."""

from __future__ import annotations

DEPRESSION_STRONG_KEYWORDS: list[str] = [
    "muốn chết",
    "muon chet",
    "tự tử",
    "tu tu",
    "không muốn sống",
    "khong muon song",
    "không thiết sống",
    "khong thiet song",
    "muốn biến mất",
    "muon bien mat",
    "muốn tan biến",
    "muon tan bien",
    "muốn ngủ mãi",
    "muon ngu mai",
    "kết thúc cuộc đời",
    "ket thuc cuoc doi",
    "chấm dứt cuộc đời",
    "cham dut cuoc doi",
    "không còn lý do sống",
    "khong con ly do song",
    "sống vô nghĩa",
    "song vo nghia",
    "cuộc sống vô nghĩa",
    "cuoc song vo nghia",
    "vô nghĩa",
    "vo nghia",
    "tuyệt vọng",
    "tuyet vong",
    "trầm cảm",
    "tram cam",
    "rối loạn trầm cảm",
    "roi loan tram cam",
    "đau khổ quá",
    "dau kho qua",
    "không chịu nổi nữa",
    "khong chiu noi nua",
    "không thể chịu nổi",
    "khong the chiu noi",
    "chỉ muốn buông xuôi",
    "chi muon buong xuoi",
    "buông xuôi tất cả",
    "buong xuoi tat ca",
    "không còn hy vọng",
    "khong con hy vong",
    "không còn tương lai",
    "khong con tuong lai",
    "chẳng còn gì để mất",
    "chang con gi de mat",
]

DEPRESSION_MEDIUM_KEYWORDS: list[str] = [
    "cô đơn",
    "co don",
    "mệt mỏi",
    "met moi",
    "áp lực",
    "ap luc",
    "stress",
    "mất ngủ",
    "mat ngu",
    "kiệt sức",
    "kiet suc",
    "burnout",
    "không còn động lực",
    "khong con dong luc",
    "mất động lực",
    "mat dong luc",
    "chán đời",
    "chan doi",
    "chán nản",
    "chan nan",
    "trống rỗng",
    "trong rong",
    "suy sụp",
    "suy sup",
    "bất lực",
    "bat luc",
    "lo âu",
    "lo au",
    "overthinking",
    "khóc một mình",
    "khoc mot minh",
    "không ai hiểu",
    "khong ai hieu",
    "áp lực gia đình",
    "ap luc gia dinh",
    "áp lực học tập",
    "ap luc hoc tap",
    "áp lực công việc",
    "ap luc cong viec",
    "mất phương hướng",
    "mat phuong huong",
    "tự ti",
    "tu ti",
    "ghét bản thân",
    "ghet ban than",
    "mất niềm tin",
    "mat niem tin",
    "không muốn nói chuyện",
    "khong muon noi chuyen",
    "cạn năng lượng",
    "can nang luong",
    "mệt quá",
    "met qua",
    "buồn quá",
    "buon qua",
    "đau lòng",
    "dau long",
    "tổn thương",
    "ton thuong",
]

NORMAL_KEYWORDS: list[str] = [
    "video hay",
    "hay quá",
    "hay qua",
    "cảm ơn",
    "cam on",
    "vui quá",
    "vui qua",
    "bổ ích",
    "bo ich",
    "ủng hộ",
    "ung ho",
    "hài quá",
    "hai qua",
    "thích quá",
    "thich qua",
    "tuyệt vời",
    "tuyet voi",
    "ý nghĩa quá",
    "y nghia qua",
    "cười xỉu",
    "cuoi xiu",
    "giải trí",
    "giai tri",
    "dễ thương",
    "de thuong",
    "đáng yêu",
    "dang yeu",
    "học được nhiều",
    "hoc duoc nhieu",
    "cảm động quá",
    "cam dong qua",
    "xem cuốn",
    "xem cuon",
    "quá đỉnh",
    "qua dinh",
    "đỉnh quá",
    "dinh qua",
    "rất hay",
    "rat hay",
    "thật ý nghĩa",
    "that y nghia",
    "chúc mừng",
    "chuc mung",
    "iu quá",
    "iu qua",
    "yêu quá",
    "yeu qua",
]

# Các cụm này không đảo nhãn trực tiếp, nhưng đánh dấu need_review vì dễ gây sai ngữ cảnh.
REVIEW_CONTEXT_KEYWORDS: list[str] = [
    "đừng tự tử",
    "dung tu tu",
    "không nên tự tử",
    "khong nen tu tu",
    "đừng nghĩ quẩn",
    "dung nghi quan",
    "hãy đi khám",
    "hay di kham",
    "tìm chuyên gia",
    "tim chuyen gia",
    "gọi đường dây nóng",
    "goi duong day nong",
    "hãy chia sẻ",
    "hay chia se",
    "cố lên",
    "co len",
    "mong bạn ổn",
    "mong ban on",
    "chết cười",
    "chet cuoi",
    "cười chết",
    "cuoi chet",
]
