"""Sinh và quản lý danh sách keyword tiếng Việt cho quá trình crawl."""

from __future__ import annotations

from collections.abc import Iterable

from yt_depression_crawler.core.config import ADDITIONAL_KEYWORDS, MAX_KEYWORDS


DEFAULT_KEYWORDS: list[str] = [
    "trầm cảm",
    "tôi bị trầm cảm",
    "dấu hiệu trầm cảm",
    "vượt qua trầm cảm",
    "sống với trầm cảm",
    "cô đơn",
    "cảm thấy cô đơn",
    "nỗi cô đơn",
    "tâm sự đêm khuya",
    "tâm sự buồn",
    "mệt mỏi cuộc sống",
    "chán nản cuộc sống",
    "không còn động lực",
    "mất động lực học tập",
    "áp lực học tập",
    "stress học đường",
    "áp lực thi cử",
    "áp lực điểm số",
    "lo âu",
    "rối loạn lo âu",
    "căng thẳng kéo dài",
    "stress công việc",
    "áp lực công việc",
    "burnout",
    "kiệt sức công việc",
    "mất ngủ",
    "mất ngủ vì stress",
    "suy nghĩ tiêu cực",
    "tuyệt vọng",
    "muốn biến mất",
    "không ai hiểu mình",
    "cảm giác trống rỗng",
    "khóc một mình",
    "thất tình",
    "đau khổ sau chia tay",
    "buồn vì thất tình",
    "áp lực gia đình",
    "mâu thuẫn gia đình",
    "bị bố mẹ tạo áp lực",
    "không được công nhận",
    "tự ti bản thân",
    "ghét bản thân",
    "mất niềm tin",
    "không muốn nói chuyện với ai",
    "sống vô nghĩa",
    "cần người lắng nghe",
    "tâm sự tuổi trẻ",
    "chữa lành nỗi đau",
    "vượt qua áp lực",
    "sức khỏe tinh thần",
    "tôi thấy cô đơn",
    "tôi thấy mệt mỏi",
    "tôi không ổn",
    "mình không ổn",
    "tôi kiệt sức",
    "mình kiệt sức",
    "tôi mất ngủ",
    "đêm không ngủ được",
    "khó ngủ",
    "rối loạn giấc ngủ",
    "mất ngủ kéo dài",
    "thức trắng đêm",
    "overthinking ban đêm",
    "suy nghĩ quá nhiều",
    "nghĩ nhiều mệt mỏi",
    "tâm sự một mình",
    "tâm sự với người lạ",
    "tâm sự radio",
    "podcast tâm sự",
    "chuyện buồn cuộc sống",
    "nỗi buồn không tên",
    "nhạc buồn tâm trạng",
    "nhạc chữa lành",
    "nhạc cho người cô đơn",
    "nhạc thất tình",
    "nhạc buồn đêm khuya",
    "mưa buồn tâm trạng",
    "tâm trạng buồn",
    "buồn không lý do",
    "cảm xúc tiêu cực",
    "năng lượng tiêu cực",
    "cạn năng lượng",
    "kiệt quệ tinh thần",
    "suy sụp tinh thần",
    "khủng hoảng tinh thần",
    "khủng hoảng tuổi 20",
    "khủng hoảng tuổi trẻ",
    "mất phương hướng",
    "lạc lõng",
    "cảm thấy lạc lõng",
    "không có ai bên cạnh",
    "không ai lắng nghe",
    "không ai quan tâm",
    "không ai thương mình",
    "không ai cần mình",
    "không muốn gặp ai",
    "không muốn ra ngoài",
    "thu mình lại",
    "sợ giao tiếp",
    "ngại giao tiếp",
    "lo âu xã hội",
    "rối loạn hoảng sợ",
    "cơn hoảng loạn",
    "panic attack",
    "bất an",
    "luôn thấy bất an",
    "sợ hãi vô cớ",
    "mệt mỏi vì gia đình",
    "gia đình không hiểu mình",
    "bố mẹ không hiểu con",
    "áp lực từ bố mẹ",
    "áp lực làm con ngoan",
    "áp lực kỳ vọng gia đình",
    "bị so sánh với người khác",
    "bố mẹ so sánh",
    "mâu thuẫn với bố mẹ",
    "cãi nhau với gia đình",
    "tổn thương gia đình",
    "áp lực tài chính",
    "áp lực tiền bạc",
    "nợ nần áp lực",
    "thất nghiệp áp lực",
    "mất việc",
    "chán việc",
    "kiệt sức vì công việc",
    "mệt mỏi công sở",
    "toxic workplace",
    "môi trường làm việc độc hại",
    "sếp toxic",
    "áp lực deadline",
    "deadline dí",
    "burnout công sở",
    "chán đi làm",
    "muốn nghỉ việc",
    "mất động lực đi làm",
    "áp lực đại học",
    "áp lực thi đại học",
    "áp lực học sinh",
    "áp lực sinh viên",
    "stress sinh viên",
    "stress mùa thi",
    "áp lực điểm thi",
    "sợ rớt môn",
    "rớt môn",
    "chán học",
    "mất động lực học",
    "không muốn đi học",
    "bị bắt nạt",
    "bạo lực học đường",
    "cô lập ở trường",
    "không có bạn bè",
    "tự ti ngoại hình",
    "tự ti học tập",
    "tự ti giao tiếp",
    "ghét chính mình",
    "không chấp nhận bản thân",
    "cảm thấy vô dụng",
    "tôi vô dụng",
    "mình vô dụng",
    "không làm được gì",
    "luôn thất bại",
    "sợ thất bại",
    "mất hy vọng",
    "không còn hy vọng",
    "không còn tương lai",
    "tương lai mịt mờ",
    "không biết sống để làm gì",
    "sống để làm gì",
    "đời vô nghĩa",
    "cuộc đời vô nghĩa",
    "muốn buông xuôi",
    "buông xuôi tất cả",
    "không chịu nổi nữa",
    "không thể chịu nổi",
    "muốn ngủ mãi",
    "chỉ muốn ngủ mãi",
    "muốn tan biến",
    "không muốn tồn tại",
    "không thiết sống",
    "không còn lý do sống",
    "muốn chết",
    "nghĩ đến cái chết",
    "ý định tự tử",
    "tự tử",
    "đừng tự tử",
    "vượt qua ý định tự tử",
    "phòng chống tự tử",
    "dấu hiệu muốn tự tử",
    "cứu tôi với",
    "ai cứu tôi với",
    "cần được giúp đỡ",
    "cần ai đó nói chuyện",
    "cần người tâm sự",
    "cần người chia sẻ",
    "xin lời khuyên tâm lý",
    "tư vấn tâm lý",
    "trị liệu tâm lý",
    "đi khám tâm lý",
    "gặp bác sĩ tâm lý",
    "chuyên gia tâm lý",
    "rối loạn cảm xúc",
    "rối loạn lưỡng cực",
    "rối loạn stress sau sang chấn",
    "sang chấn tâm lý",
    "tổn thương tâm lý",
    "chữa lành tâm lý",
    "chữa lành đứa trẻ bên trong",
    "inner child",
    "yêu bản thân",
    "học cách yêu bản thân",
    "tha thứ cho bản thân",
    "vượt qua nỗi đau",
    "vượt qua cô đơn",
    "vượt qua thất tình",
    "vượt qua chia tay",
    "sau chia tay",
    "người yêu cũ",
    "bị phản bội",
    "bị bỏ rơi",
    "cảm giác bị bỏ rơi",
    "lụy tình",
    "đau sau chia tay",
    "không quên được người yêu cũ",
    "tình yêu toxic",
    "mối quan hệ độc hại",
    "gaslighting",
    "bị thao túng tâm lý",
    "tổn thương trong tình yêu",
    "chán đời tuổi trẻ",
    "áp lực tuổi 20",
    "áp lực tuổi 25",
    "khủng hoảng hiện sinh",
    "existential crisis",
    "cảm giác trống rỗng trong lòng",
    "đêm khuya suy nghĩ",
    "một mình trong phòng",
    "khóc trong im lặng",
    "nước mắt đêm khuya",
    "mệt mỏi nhưng không nói ra",
    "nụ cười che giấu nỗi buồn",
    "ẩn sau nụ cười",
    "tâm sự người trẻ",
    "người trẻ trầm cảm",
    "sinh viên trầm cảm",
    "học sinh trầm cảm",
    "nhân viên văn phòng trầm cảm",
    "mẹ bỉm trầm cảm",
    "trầm cảm sau sinh",
    "trầm cảm tuổi dậy thì",
    "trầm cảm ở người trẻ",
    "dấu hiệu lo âu",
    "dấu hiệu stress",
    "dấu hiệu burnout",
    "dấu hiệu kiệt sức",
    "cách vượt qua trầm cảm",
    "cách giảm stress",
    "cách ngủ ngon",
    "cách hết overthinking",
    "cách vượt qua cô đơn",
    "cách lấy lại động lực",
    "làm sao để có động lực",
    "làm sao để bớt buồn",
    "làm sao để hết mệt mỏi",
    "làm sao để yêu bản thân",
]


def _normalize_keyword(keyword: str) -> str:
    return " ".join(keyword.strip().split()).lower()


def unique_keywords(keywords: Iterable[str]) -> list[str]:
    """Loại trùng keyword nhưng vẫn giữ thứ tự ban đầu."""
    seen: set[str] = set()
    result: list[str] = []

    for keyword in keywords:
        normalized = _normalize_keyword(keyword)
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        result.append(normalized)

    return result


def get_keywords(
    additional_keywords: Iterable[str] | None = None,
    max_keywords: int | None = MAX_KEYWORDS,
) -> list[str]:
    """Trả về danh sách keyword mặc định + keyword bổ sung trong config."""
    merged = list(DEFAULT_KEYWORDS)
    merged.extend(ADDITIONAL_KEYWORDS)

    if additional_keywords:
        merged.extend(additional_keywords)

    keywords = unique_keywords(merged)
    if max_keywords is not None:
        return keywords[:max_keywords]
    return keywords
