"""BERTopic inference engine for topic assignment.

Loads the trained BERTopic model and assigns topics to input texts.
"""

from __future__ import annotations

import json
import logging
import pickle
from pathlib import Path
from typing import Optional

import numpy as np
from sentence_transformers import SentenceTransformer

# Disable proxies
import os
for _var in ["http_proxy", "https_proxy", "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "all_proxy"]:
    os.environ.pop(_var, None)

# ── Paths ─────────────────────────────────────────────────────────────────────
# Backend code is in /app/ (copied from web_demo/backend/)
# Models are mounted at /app/models/
_BACKEND_DIR = Path(__file__).resolve().parent  # /app/inference
_APP_DIR = _BACKEND_DIR.parent  # /app/

BERTOPIC_MODEL_FILE = _APP_DIR / "models" / "bertopic" / "bertopic_model.pkl"
BERTOPIC_METRICS_FILE = _APP_DIR / "models" / "bertopic" / "bertopic_metrics.json"

logger = logging.getLogger(__name__)

# ── Topic label cache ─────────────────────────────────────────────────────────

_TOPIC_LABELS: Optional[dict[int, str]] = None
_TOPIC_METRICS: Optional[dict] = None


def _load_topic_labels() -> dict[int, str]:
    """Load topic ID → label mapping from BERTopic metrics."""
    global _TOPIC_LABELS
    if _TOPIC_LABELS is not None:
        return _TOPIC_LABELS

    _TOPIC_LABELS = {}
    if BERTOPIC_METRICS_FILE.exists():
        with open(BERTOPIC_METRICS_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        for entry in data.get("topic_distribution", []):
            tid = entry.get("topic_id", 0)
            words = entry.get("top_words", [])
            if words:
                label = " | ".join([w["word"] for w in words[:5]])
            else:
                label = f"topic_{tid}"
            _TOPIC_LABELS[tid] = label
    return _TOPIC_LABELS


def _load_topic_metrics() -> dict:
    """Load full BERTopic metrics."""
    global _TOPIC_METRICS
    if _TOPIC_METRICS is not None:
        return _TOPIC_METRICS
    _TOPIC_METRICS = {}
    if BERTOPIC_METRICS_FILE.exists():
        with open(BERTOPIC_METRICS_FILE, "r", encoding="utf-8") as f:
            _TOPIC_METRICS = json.load(f)
    return _TOPIC_METRICS


# ── Engine ────────────────────────────────────────────────────────────────────

class BERTopicEngine:
    """Singleton BERTopic inference engine.

    Falls back to metrics JSON if the pickle model is incompatible
    (which happens across bertopic/sentence-transformers version bumps).
    """

    _instance: Optional["BERTopicEngine"] = None

    def __init__(self) -> None:
        self.topic_model = None
        self.embedder = None
        self._model_error: Optional[str] = None

        # Try to load the full pickled model; degrade gracefully if it fails.
        #
        # SECURITY NOTE: pickle.load() is used here on a file generated by our own
        # BERTopic training script and stored in the project's models/ directory.
        # This is a trusted source (not external/unauthenticated input).
        # Alternatives considered:
        #   - safetensors: BERTopic has no safetensors export API
        #   - weights_only=True: BERTopic model objects cannot survive restricted pickle
        #   - HMAC signing: requires regenerating all existing model files
        # If the model directory is replaced at runtime (e.g. volume mount from an
        # untrusted host), this becomes a risk — keep the models/ dir trusted.
        if BERTOPIC_MODEL_FILE.exists():
            try:
                logger.info("Loading BERTopic model from %s", BERTOPIC_MODEL_FILE)
                with open(BERTOPIC_MODEL_FILE, "rb") as f:
                    self.topic_model = pickle.load(f)
                logger.info("BERTopic full model loaded")
            except Exception as e:
                self._model_error = str(e)
                logger.warning(
                    "BERTopic pickle load failed (%s) — using metrics JSON only",
                    e,
                )

        # Lazy-load the embedder only if needed (avoid slow startup).
        self.topic_labels = _load_topic_labels()
        logger.info("BERTopic engine ready (%d topics cached)", len(self.topic_labels))

    @classmethod
    def get_instance(cls) -> "BERTopicEngine":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def _ensure_full_model(self) -> bool:
        """Lazy-load the embedder + verify model. Returns True if usable."""
        if self.topic_model is None:
            return False
        if self.embedder is None:
            try:
                logger.info("Loading sentence-transformer embedder...")
                self.embedder = SentenceTransformer(
                    "paraphrase-multilingual-MiniLM-L12-v2"
                )
            except Exception as e:
                logger.warning("Embedder load failed: %s", e)
                return False
        return True

    def predict_topic(self, text: str) -> dict:
        """Assign a topic to a single text."""
        result = self.predict_topics([text])
        return result[0] if result else {"topic_id": -1, "topic_name": None, "probability": 0.0}

    def predict_topics(self, texts: list[str]) -> list[dict]:
        """Assign topics to a batch of texts. Returns empty topic if model unavailable."""
        if not texts:
            return []

        if not self._ensure_full_model():
            return [
                {"topic_id": -1, "topic_name": None, "probability": 0.0}
                for _ in texts
            ]

        try:
            embeddings = self.embedder.encode(
                [str(t) for t in texts],
                show_progress_bar=False,
                batch_size=64,
                normalize_embeddings=True,
            )
            topics, probs = self.topic_model.transform(texts, embeddings=embeddings)
        except Exception as e:
            logger.warning("Topic prediction failed: %s", e)
            return [
                {"topic_id": -1, "topic_name": None, "probability": 0.0}
                for _ in texts
            ]

        results = []
        for tid, prob in zip(topics, probs):
            if isinstance(prob, np.ndarray):
                prob = float(np.max(prob))
            elif not isinstance(prob, float):
                prob = float(prob)

            label = self.topic_labels.get(int(tid), f"topic_{tid}")
            results.append({
                "topic_id": int(tid),
                "topic_name": label,
                "probability": round(prob, 4),
            })
        return results

    def get_top_topics(self, limit: int = 20) -> list[dict]:
        """Return the top N most frequent meaningful topics (excluding -1 outliers).

        Reads directly from metrics JSON — does not require the pickled model.
        """
        metrics = _load_topic_metrics()
        distribution = metrics.get("topic_distribution", [])

        # Filter out outliers (topic -1) and sort by count descending
        meaningful = [t for t in distribution if t["topic_id"] != -1]
        meaningful.sort(key=lambda x: x["document_count"], reverse=True)
        top = meaningful[:limit]

        results = []
        total = sum(t["document_count"] for t in meaningful)
        for entry in top:
            tid = entry["topic_id"]
            words = [w["word"] for w in entry.get("top_words", [])[:5]]
            results.append({
                "id": tid,
                "name": self.topic_labels.get(tid, f"topic_{tid}"),
                "keywords": words,
                "count": entry["document_count"],
                "percentage": round(entry["document_count"] / total * 100, 2) if total > 0 else 0,
                "examples": [],  # Could be populated from corpus if needed
            })
        return results

    def reload(self) -> None:
        """Hot-reload the model."""
        global _TOPIC_LABELS, _TOPIC_METRICS
        _TOPIC_LABELS = None
        _TOPIC_METRICS = None
        BERTopicEngine._instance = None
        BERTopicEngine._instance = BERTopicEngine()


# ── Module-level convenience ──────────────────────────────────────────────────

_engine: Optional[BERTopicEngine] = None


def get_engine() -> BERTopicEngine:
    global _engine
    if _engine is None:
        _engine = BERTopicEngine.get_instance()
    return _engine


def get_topic_for_text(text: str) -> dict:
    """Convenience: get topic for a single text."""
    return get_engine().predict_topic(text)


def get_topics(limit: int = 20) -> list[dict]:
    """Convenience: get top N topics."""
    return get_engine().get_top_topics(limit=limit)
